name: Windows MinGW 5.15.2
on:
    push:
        paths:
            - '*.txt'
            - 'src/**'
            - 'res/**'
            - '.cmake/**'
            - '.github/workflows/windows-mingw-qt5.yml'
    pull_request:
        paths:
            - '*.txt'
            - 'src/**'
            - 'res/**'
            - '.cmake/**'
            - '.github/workflows/windows-mingw-qt5.yml'

jobs:
    build:
        name: Build
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [windows-latest]
                include:
                    - qt_arch: win64_mingw81
                      qt_ver: 5.15.2
                      qt_tools: "tools_mingw,qt.tools.win64_mingw810"
                      qt_tools_mingw_install: mingw810_64

        env:
            targetName: SecAssistUp.exe
            fileName: SecAssistUp
        steps:
            - name: Check out repository
              uses: actions/checkout@v3
              with:
                submodules: recursive

            - name: Setup ninja
              uses: seanmiddleditch/gha-setup-ninja@master
              with:
                version: 1.10.2

            # Reference: https://github.com/jurplel/install-qt-action
            # Reference: https://ddalcino.github.io/aqt-list-server/
            - name: Install Qt
              uses: jurplel/install-qt-action@v3
              with:
                version: ${{ matrix.qt_ver }}
                arch: ${{ matrix.qt_arch }}
                cache: ${{steps.cache-qt.outputs.cache-hit}}
                tools: ${{ matrix.qt_tools }}

            - name: Get Mingw folder info
              shell: pwsh
              run: |
                Get-ChildItem ${{ runner.workspace }}
                Get-ChildItem ${{ runner.workspace }}\Qt
                Get-ChildItem ${{ runner.workspace }}\Qt\${{ matrix.qt_ver }}
                Get-ChildItem ${{ runner.workspace }}\Qt\Tools
                Get-ChildItem ${{ runner.workspace }}\Qt\Tools\${{ matrix.qt_tools_mingw_install }}\bin

            - name: Qt5 environment configuration
              if: ${{ startsWith( matrix.qt_ver, 5 ) }}
              shell: pwsh
              run: |
                $mingwPath = "${{ runner.workspace }}\Qt\Tools\${{ matrix.qt_tools_mingw_install }}\bin"
                Write-Output "${{ env.Qt5_DIR }}/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
                Write-Output $mingwPath | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
                # 验证编译器
                Write-Host "Verifying MinGW compiler:"
                & "$mingwPath\gcc.exe" --version

            - name: where is cmake & where is mingw32-make
              shell: pwsh
              run: |
                Get-Command -Name 'cmake' | Format-List
                Get-Command -Name 'mingw32-make' | Format-List

            - name: Verify tools
              shell: pwsh
              run: |
                Write-Host "Qt Version: ${{ matrix.qt_ver }}"
                Write-Host "Qt Arch: ${{ matrix.qt_arch }}"
                Write-Host "MinGW Version: ${{ matrix.mingw_ver }}"
                Write-Host "Qt5_DIR: ${{ env.Qt5_DIR }}"
                Get-Command -Name 'cmake' | Format-List
                Get-Command -Name 'mingw32-make' | Format-List
                Get-Command -Name 'gcc' | Format-List
                gcc --version

            - name: mingw-build
              id: build
              shell: cmd
              run: |
                mkdir build
                cd build
                ninja --version
                cmake -DCMAKE_MESSAGE_LOG_LEVEL=STATUS -DCMAKE_PREFIX_PATH=D:\a\SecAssistUp\Qt\${{ matrix.qt_ver }}\mingw_64 -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Release -GNinja ..
                cmake --build . --target all --config Release --parallel

            - name: package
              id: package      
              env:
                archiveName: ${{ env.fileName }}-${{ matrix.qt_arch }}-${{ matrix.qt_ver }}
              shell: pwsh
              run: |
                & scripts\windows-mingw-publish.ps1 ${env:archiveName} ${env:targetName}
                 $name = ${env:archiveName}
                 echo "::set-output name=packageName::$name"

            - uses: actions/upload-artifact@v4
              with:
                name: ${{ steps.package.outputs.packageName }}
                path: dist

            - name: Convert to UTF-8 with BOM
              shell: pwsh
              run: |
                # InstallerScript.iss.in 默认生成 UTF-8 without BOM格式，脚本中的中文打包时会出现乱码，所以此处需要转换编码格式
                # 读取生成的文件并添加BOM
                $content = Get-Content -Path ./package/InstallerScript.iss -Raw -Encoding UTF8
                # 添加UTF-8 BOM并保存
                [System.IO.File]::WriteAllText("./package/InstallerScript.iss", $content, [System.Text.Encoding]::UTF8)

            - uses: actions/upload-artifact@v4
              with:
                name: InstallerScript.iss
                path: ./package/InstallerScript.iss

            - name: Print package/InstallerScript.iss Content
              shell: pwsh
              run: |
                Get-Content ./package/InstallerScript.iss

            - name: inno setup install
              uses: zhuzichu520/inno-setup-action@v1.0.1
              with:
                  filepath: ./package/InstallerScript.iss

            - uses: actions/upload-artifact@v4
              if: ${{ !startsWith(github.event.ref, 'refs/tags/') }}
              with:
                # Default Tag Name is 1.0.0
                name: ${{ env.fileName }}-1.0.0_setup.exe
                path: ./package/${{ env.fileName }}-1.0.0_setup.exe

            # - name: uploadRelease
            #   if: startsWith(github.event.ref, 'refs/tags/')
            #   uses: svenstaro/upload-release-action@v2
            #   with:
            #     repo_token: ${{ secrets.GITHUB_TOKEN }}
            #     file: ./package/${{ env.fileName }}-${{ github.ref_name }}_setup.exe
            #     asset_name: ${{ env.fileName }}_${{ github.ref_name }}_${{ matrix.qt_arch }}_Qt${{ matrix.qt_ver }}_setup.exe
            #     tag: ${{ github.ref }}
            #     overwrite: true
            # - name: Rename Upload Assets
            #   if: startsWith(github.event.ref, 'refs/tags/')
            #   shell: pwsh
            #   run: |
            #     Rename-Item -Path ./package/${{ env.fileName }}-${{ github.ref_name }}_setup.exe -NewName ${{ env.fileName }}_${{ github.ref_name }}_${{ matrix.qt_arch }}_Qt${{ matrix.qt_ver }}_setup.exe -Force -WhatIf
            #     Rename-Item -Path ./package/${{ env.fileName }}-${{ github.ref_name }}_setup.exe -NewName ${{ env.fileName }}_${{ github.ref_name }}_${{ matrix.qt_arch }}_Qt${{ matrix.qt_ver }}_setup.exe -Force

            - name: Create Release and Upload Assets
              if: startsWith(github.event.ref, 'refs/tags/')
              uses: softprops/action-gh-release@v2
              with:
                files: |
                  # ./package/${{ env.fileName }}_${{ github.ref_name }}_${{ matrix.qt_arch }}_Qt${{ matrix.qt_ver }}_setup.exe
                  ./package/${{ env.fileName }}-${{ github.ref_name }}_setup.exe
                name: ${{ github.ref_name }}
                body_path: ./CHANGELOG.md
                generate_release_notes: true

              
